//types
const SEARCH_CHARACTERS = 'SEARCH_CHARACTERS'

const SET_NAME_CHARACTER = 'SET_NAME_CHARACTER'

const SET_SELECTED_CHARACTER = 'SELECTED_CHARACTER' 

export default {
    SEARCH_CHARACTERS,
    SET_NAME_CHARACTER,
    SET_SELECTED_CHARACTER  
}